### ISSUE TITLE
Readme do projeto

### ISSUE THREAD

**Issue by lucassouzavieira** [jherfson/SOR#1]
Olá, colegas

Você podem disponibilizar um README do projeto descrevendo o que ele é, como usar e como contribuir com o projeto.

Servirá também no port para C++.

A issue pode ficar em discussão.

**Comment by herissonchaves** [comment]
Ele gerencia arquivos, gera um arquivo txt com os resultados da simulação. Jherfson sabe explicar melhor.

**Comment by lucassouzavieira** [comment]
A entrada de dados é feita através de um arquivo texto ?

**Comment by jherfson** [comment]
Na verdade esse programa foi criado pra gerenciar dados. Os dados que são extraídos, são gerados do GULP "Um programa de simulação classica".

**Comment by jherfson** [comment]
http://www.staff.amu.edu.pl/~magchem/GULP/gulp.html

**Comment by lucassouzavieira** [comment]
Ah sim, saquei. O documento que ele gera é aquele que você me passou, @jherfson ?

**Comment by jherfson** [comment]
Isso mesmo @lucassouzavieira

**Comment by lucassouzavieira** [comment]
Entendo. Nesse caso, só queria tirar uma dúvida. Esse código do SOR faz cálculos em cima dos dados do arquivo gerado do GULP ?

**Comment by jherfson** [comment]
O SOR não faz cálculo. Ele extraí os dados.

**Comment by jherfson** [comment]
Quem faz os  cálculos é o GULP.

**Comment by lucassouzavieira** [comment]
Show. Nesse caso, melhor fazer com PHP mesmo, já que basicamente vamos processar arquivos e strings.

**Comment by herissonchaves** [comment]
perfeito
